feat: add mode option to artifact registry repository
sparkfabrik/terraform-google-gcp-artifact-registry pull request #8
Opened 2024-04-09 10:28 UTC by FabrizioCafolla

2024-04-09 16:30 UTC, FabrizioCafolla commented
We waiting for the implementation on an [issue](https://github.com/hashicorp/terraform-provider-google/issues/17751) that allows using `customRepository`

2024-04-24 14:19 UTC, FabrizioCafolla commented
This new feature for managing the docker custom registry require a version `hashicorp/google >= 5.26.0`

2024-05-02 10:06 UTC, Monska85 requested changes

2024-05-02 10:06 UTC, Monska85 commented on CHANGELOG.md
> +- FEAT: Upgrade `hashicorp/google` provider to `>= 5.26.0`
```suggestion
- FEATURE: Create an artifact registry repository in remote or virtual mode
- FEATURE: Upgrade `hashicorp/google` provider to `>= 5.26.0`
```

I would prefer to keep this convention, as described in the _header_ of this file.

2024-05-02 10:06 UTC, Monska85 commented on examples/variables.tf
> +}
Add the `type` to this variable (`string`).

2024-05-02 10:10 UTC, FabrizioCafolla commented on examples/variables.tf
> +}
Done

2024-05-02 10:13 UTC, Monska85 approved these changes
LGTM :+1:

2024-05-02 10:13 UTC, merged